package com.common.command;

public enum CommandType {
    INSERT, CLEAR, COUNT_BY_TRANSPORT, REPLACE_IF_LOWE, EXECUTE_SCRIPT, HELP, INFO, REMOVE_ANY_BY_FURNISH,
    REMOVE_KEY, REMOVE_GREATER, SHOW, REMOVE_ALL_BY_FURNISH, UPDATE, EXIT, HISTORY, AUTH
}
